In [305]:
import pandas as pd
import sys
import csv
import numpy as np
import matplotlib.pyplot as plt
import seaborn as seabornInstance
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics
import pandas as pd
import nltk
from sklearn.feature_extraction.text import CountVectorizer

In [306]:
import chardet    
rawdata = open('source.csv', 'rb').read()
result = chardet.detect(rawdata)
charenc = result['encoding']
print(charenc)

Big5


In [307]:
df = pd.read_csv('source.csv',encoding=r'Big5')

In [308]:
df['發生時段']

0       08~10
1       00~02
2       00~02
3       06~08
4       10~12
        ...  
3267    09~11
3268    12~14
3269    06~08
3270    15~17
3271    18~20
Name: 發生時段, Length: 3272, dtype: object

In [309]:
time_zone = []
for r in df['發生時段']:
    if(r == '00~02' or r == '03~05' or r == '04~06' or r == '05~07'):
        time_zone.append('midnight')
    elif(r == '06~08' or r =='08~10' or r == '09~11' or r == '10~12' or r == '11~13'):
        time_zone.append('morning')
    elif(r == '12~14' or r == '14~16' or r == '15~17' or r == '15~18' or r == '16~18' or r == '17~19'):
        time_zone.append('afternoon')
    else:
        time_zone.append('night')


In [310]:
df['time_zone'] = time_zone

In [311]:
df.loc[df['time_zone']=='morning'].to_csv('morning.csv',encoding='utf-8-sig')

In [312]:
df

編號    案類     發生日期   發生時段                        發生地點  time_zone
0        1  住宅竊盜  1030623  08~10            臺北市中正區廈門街91~120號    morning
1        2  住宅竊盜  1040101  00~02           臺北市文山區萬美里萬寧街1~30號   midnight
2        3  住宅竊盜  1040101  00~02  臺北市信義區富台里忠孝東路5段295巷6弄1~30號   midnight
3        4  住宅竊盜  1040101  06~08         臺北市中山區新生北路1段91~120號    morning
4        5  住宅竊盜  1040101  10~12         臺北市文山區明興里興隆路4段1~30號    morning
...    ...   ...      ...    ...                         ...        ...
3267  3268  住宅竊盜  1101102  09~11    臺北市文山區萬興里009鄰指南路2段61~90號    morning
3268  3269  住宅竊盜  1101104  12~14         臺北市萬華區西園路2段13巷1~30號  afternoon
3269  3270  住宅竊盜  1101113  06~08             臺北市中正區紹興南街1~30號    morning
3270  3271  住宅竊盜  1101114  15~17            臺北市中正區西藏路91~120號  afternoon
3271  3272  住宅竊盜  1101117  18~20       臺北市大同區長安西路172巷3弄1~30號      night

[3272 rows x 6 columns]

In [313]:
list = []

In [314]:
for r in df['發生地點']:
    list.append(r[0:6])
len(list)

3272

In [315]:
df['locate'] = list

In [316]:
import pandas as pd

temp = pd.Timestamp('2014-06-23')
print(temp.dayofweek, temp.day_name())

0 Monday


In [317]:
temp=pd.Timestamp(20201125)
print(temp.dayofweek,temp.day_name())

3 Thursday


In [318]:
list = []
for r in df['發生日期']:
    r = str(r)
    y = str(int(r[:3]) + 1911)
    m = r[3:5]
    d = r[5:7]
    r = y + '-' + m + '-' + d
    temp = pd.Timestamp(r)
    strtemp = ''
    if(temp.dayofweek == 0):
        strtemp = '周一'
    elif(temp.dayofweek == 1):
        strtemp = '周二'
    elif(temp.dayofweek == 2):
        strtemp = '周三'
    elif(temp.dayofweek == 3):
        strtemp = '周四'
    elif(temp.dayofweek == 4):
        strtemp = '周五'
    elif(temp.dayofweek == 5):
        strtemp = '周六'
    elif(temp.dayofweek == 6):
        strtemp = '周日'
    list.append(strtemp)

In [319]:
list

['周一',
 '周四',
 '周四',
 '周四',
 '周四',
 '周五',
 '周五',
 '周五',
 '周五',
 '周日',
 '周日',
 '周一',
 '周一',
 '周一',
 '周一',
 '周一',
 '周一',
 '周二',
 '周二',
 '周三',
 '周四',
 '周五',
 '周五',
 '周五',
 '周六',
 '周日',
 '周一',
 '周一',
 '周一',
 '周二',
 '周三',
 '周三',
 '周四',
 '周四',
 '周四',
 '周四',
 '周四',
 '周五',
 '周六',
 '周六',
 '周六',
 '周六',
 '周日',
 '周日',
 '周日',
 '周日',
 '周一',
 '周二',
 '周三',
 '周三',
 '周三',
 '周三',
 '周四',
 '周四',
 '周五',
 '周五',
 '周五',
 '周六',
 '周一',
 '周一',
 '周一',
 '周一',
 '周二',
 '周二',
 '周二',
 '周二',
 '周二',
 '周二',
 '周二',
 '周三',
 '周四',
 '周四',
 '周五',
 '周六',
 '周日',
 '周日',
 '周日',
 '周日',
 '周一',
 '周一',
 '周二',
 '周三',
 '周四',
 '周四',
 '周四',
 '周五',
 '周五',
 '周六',
 '周六',
 '周日',
 '周一',
 '周二',
 '周二',
 '周三',
 '周四',
 '周四',
 '周四',
 '周四',
 '周五',
 '周五',
 '周六',
 '周日',
 '周日',
 '周日',
 '周日',
 '周一',
 '周一',
 '周一',
 '周一',
 '周一',
 '周一',
 '周三',
 '周四',
 '周四',
 '周四',
 '周四',
 '周五',
 '周六',
 '周日',
 '周一',
 '周一',
 '周一',
 '周一',
 '周二',
 '周二',
 '周二',
 '周三',
 '周三',
 '周三',
 '周四',
 '周四',
 '周四',
 '周五',
 '周五',
 '周五',
 '周六',
 '周六',
 '周一',
 '周三',
 '周三',
 '周三',
 '周四',
 '周四',

In [320]:
df

編號    案類     發生日期   發生時段                        發生地點  time_zone  \
0        1  住宅竊盜  1030623  08~10            臺北市中正區廈門街91~120號    morning   
1        2  住宅竊盜  1040101  00~02           臺北市文山區萬美里萬寧街1~30號   midnight   
2        3  住宅竊盜  1040101  00~02  臺北市信義區富台里忠孝東路5段295巷6弄1~30號   midnight   
3        4  住宅竊盜  1040101  06~08         臺北市中山區新生北路1段91~120號    morning   
4        5  住宅竊盜  1040101  10~12         臺北市文山區明興里興隆路4段1~30號    morning   
...    ...   ...      ...    ...                         ...        ...   
3267  3268  住宅竊盜  1101102  09~11    臺北市文山區萬興里009鄰指南路2段61~90號    morning   
3268  3269  住宅竊盜  1101104  12~14         臺北市萬華區西園路2段13巷1~30號  afternoon   
3269  3270  住宅竊盜  1101113  06~08             臺北市中正區紹興南街1~30號    morning   
3270  3271  住宅竊盜  1101114  15~17            臺北市中正區西藏路91~120號  afternoon   
3271  3272  住宅竊盜  1101117  18~20       臺北市大同區長安西路172巷3弄1~30號      night   

      locate  
0     臺北市中正區  
1     臺北市文山區  
2     臺北市信義區  
3     臺北市中山區  
4     臺北市文山區  
...      ...  
3267  臺北市文山區  
3268  臺北市萬華區  
3269  臺北市中正區  
3270  臺北市中正區  
3271  臺北市大同區  

[3272 rows x 7 columns]

In [321]:
for r in range(len(df['locate'])):
    list[r] = df['locate'][r] + list[r]

In [322]:
df['locate'] = list

In [323]:
train, test = train_test_split(df, test_size = 0.1)

In [324]:
train

編號    案類     發生日期   發生時段                        發生地點  time_zone  \
2394  2395  住宅竊盜  1071221  10~12          臺北市萬華區長泰街19巷31~60號    morning   
469    470  住宅竊盜  1040908  00~02        臺北市中山區林森北路133巷31~60號   midnight   
201    202  住宅竊盜  1040410  06~08  臺北市北投區吉利里23鄰吉利街320巷1弄1~30號    morning   
2704  2705  住宅竊盜  1080805  22~24             臺北市松山區延吉街31~60號      night   
2100  2101  住宅竊盜  1070615  00~02             臺北市南港區成福路61~90號   midnight   
...    ...   ...      ...    ...                         ...        ...   
1324  1325  住宅竊盜  1051216  22~24           臺北市內湖區江南街96巷1~30號      night   
3178  3179  住宅竊盜  1100523  23~01          臺北市中山區龍江路37巷31~60號      night   
803    804  住宅竊盜  1050228  02~04           臺北市南港區成福路181~210號      night   
1405  1406  住宅竊盜  1060202  14~16     臺北市中山區中山北路2段62巷28之1~30號  afternoon   
2700  2701  住宅竊盜  1080801  02~04          臺北市中山區德惠街193巷1~30號      night   

        locate  
2394  臺北市萬華區周五  
469   臺北市中山區周二  
201   臺北市北投區周五  
2704  臺北市松山區周一  
2100  臺北市南港區周五  
...        ...  
1324  臺北市內湖區周五  
3178  臺北市中山區周日  
803   臺北市南港區周日  
1405  臺北市中山區周四  
2700  臺北市中山區周四  

[2944 rows x 7 columns]

In [325]:
BOW_vectorizer = CountVectorizer() 

In [326]:
BOW_vectorizer.fit(train['locate'])
train_data_BOW_features = BOW_vectorizer.transform(train['locate'])
test_data_BOW_features = BOW_vectorizer.transform(test['locate'])

In [327]:
train_data_BOW_features

<2944x84 sparse matrix of type '<class 'numpy.int64'>'
	with 2944 stored elements in Compressed Sparse Row format>

In [328]:
feature_names = BOW_vectorizer.get_feature_names()
feature_names

['臺北市中山區周一',
 '臺北市中山區周三',
 '臺北市中山區周二',
 '臺北市中山區周五',
 '臺北市中山區周六',
 '臺北市中山區周四',
 '臺北市中山區周日',
 '臺北市中正區周一',
 '臺北市中正區周三',
 '臺北市中正區周二',
 '臺北市中正區周五',
 '臺北市中正區周六',
 '臺北市中正區周四',
 '臺北市中正區周日',
 '臺北市信義區周一',
 '臺北市信義區周三',
 '臺北市信義區周二',
 '臺北市信義區周五',
 '臺北市信義區周六',
 '臺北市信義區周四',
 '臺北市信義區周日',
 '臺北市內湖區周一',
 '臺北市內湖區周三',
 '臺北市內湖區周二',
 '臺北市內湖區周五',
 '臺北市內湖區周六',
 '臺北市內湖區周四',
 '臺北市內湖區周日',
 '臺北市北投區周一',
 '臺北市北投區周三',
 '臺北市北投區周二',
 '臺北市北投區周五',
 '臺北市北投區周六',
 '臺北市北投區周四',
 '臺北市北投區周日',
 '臺北市南港區周一',
 '臺北市南港區周三',
 '臺北市南港區周二',
 '臺北市南港區周五',
 '臺北市南港區周六',
 '臺北市南港區周四',
 '臺北市南港區周日',
 '臺北市士林區周一',
 '臺北市士林區周三',
 '臺北市士林區周二',
 '臺北市士林區周五',
 '臺北市士林區周六',
 '臺北市士林區周四',
 '臺北市士林區周日',
 '臺北市大同區周一',
 '臺北市大同區周三',
 '臺北市大同區周二',
 '臺北市大同區周五',
 '臺北市大同區周六',
 '臺北市大同區周四',
 '臺北市大同區周日',
 '臺北市大安區周一',
 '臺北市大安區周三',
 '臺北市大安區周二',
 '臺北市大安區周五',
 '臺北市大安區周六',
 '臺北市大安區周四',
 '臺北市大安區周日',
 '臺北市文山區周一',
 '臺北市文山區周三',
 '臺北市文山區周二',
 '臺北市文山區周五',
 '臺北市文山區周六',
 '臺北市文山區周四',
 '臺北市文山區周日',
 '臺北市松山區周一',
 '臺北市松山區周三',
 '臺北市松山區周二',
 '臺北市松山區周五',
 '臺北市松山區周六',
 '臺北市松山區周四',
 '臺北市松山區周日',

In [329]:
import nltk
import jieba
# build analyzers (bag-of-words)
BOW = CountVectorizer(tokenizer=jieba.cut) 

# apply analyzer to training data
BOW.fit(train['locate'])

train_data_BOW_features = BOW.transform(train['time_zone'])

## check dimension
train_data_BOW_features.shape

C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:489: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn("The parameter 'token_pattern' will not be used"


(2944, 25)

In [330]:
train_data_BOW_features.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [331]:
feature_names = BOW.get_feature_names()


In [332]:
train['locate']

2394    臺北市萬華區周五
469     臺北市中山區周二
201     臺北市北投區周五
2704    臺北市松山區周一
2100    臺北市南港區周五
          ...   
1324    臺北市內湖區周五
3178    臺北市中山區周日
803     臺北市南港區周日
1405    臺北市中山區周四
2700    臺北市中山區周四
Name: locate, Length: 2944, dtype: object

In [333]:
from sklearn.tree import DecisionTreeClassifier

# for a classificaiton problem, you need to provide both training & testing data
X_train = BOW.transform(train['locate'])
y_train = train['time_zone']

X_test = BOW.transform(test['locate'])
y_test = test['time_zone']

## take a look at data dimension is a good habbit  :)
print('X_train.shape: ', X_train.shape)
print('y_train.shape: ', y_train.shape)
print('X_test.shape: ', X_test.shape)
print('y_test.shape: ', y_test.shape)

X_train.shape:  (2944, 25)
y_train.shape:  (2944,)
X_test.shape:  (328, 25)
y_test.shape:  (328,)


In [334]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 1, 1],
       [1, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 1, 0],
       ...,
       [0, 0, 0, ..., 0, 1, 0],
       [1, 0, 0, ..., 0, 1, 0],
       [1, 0, 0, ..., 0, 1, 0]], dtype=int64)

In [335]:
## build DecisionTree model
DT_model = DecisionTreeClassifier(random_state=0)

## training!
DT_model = DT_model.fit(X_train, y_train)

## predict!
y_train_pred = DT_model.predict(X_train)
y_test_pred = DT_model.predict(X_test)

## so we get the pred result
y_test_pred[:20]

array(['afternoon', 'afternoon', 'night', 'night', 'afternoon', 'night',
       'morning', 'midnight', 'afternoon', 'afternoon', 'morning',
       'afternoon', 'morning', 'afternoon', 'morning', 'afternoon',
       'night', 'night', 'morning', 'midnight'], dtype=object)

In [336]:
## accuracy
from sklearn.metrics import accuracy_score

acc_train = accuracy_score(y_true=y_train, y_pred=y_train_pred)
acc_test = accuracy_score(y_true=y_test, y_pred=y_test_pred)

print('training accuracy: {}'.format(round(acc_train, 2)))
print('testing accuracy: {}'.format(round(acc_test, 2)))

training accuracy: 0.38
testing accuracy: 0.3


In [337]:
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
print('check label: ', label_encoder.classes_)
print('\n## Before convert')
print('y_train[0:4]:\n', y_train[0:4])
print('\ny_train.shape: ', y_train.shape)
print('y_test.shape: ', y_test.shape)

def label_encode(le, labels):
    enc = le.transform(labels)
    return np_utils.to_categorical(enc)

def label_decode(le, one_hot_label):
    dec = np.argmax(one_hot_label, axis=1)
    return le.inverse_transform(dec)

y_train = label_encode(label_encoder, y_train)
y_test = label_encode(label_encoder, y_test)

print('\n\n## After convert')
print('y_train[0:4]:\n', y_train[0:4])
print('\ny_train.shape: ', y_train.shape)
print('y_test.shape: ', y_test.shape)

check label:  ['afternoon' 'midnight' 'morning' 'night']

## Before convert
y_train[0:4]:
 2394     morning
469     midnight
201      morning
2704       night
Name: time_zone, dtype: object

y_train.shape:  (2944,)
y_test.shape:  (328,)


## After convert
y_train[0:4]:
 [[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

y_train.shape:  (2944, 4)
y_test.shape:  (328, 4)


In [338]:
# I/O check
input_shape = X_train.shape[1]
print('input_shape: ', input_shape)

output_shape = len(label_encoder.classes_)
print('output_shape: ', output_shape)

input_shape:  25
output_shape:  4


In [339]:
from keras.models import Model
from keras.layers import Input, Dense
from keras.layers import ReLU, Softmax

# input layer
model_input = Input(shape=(input_shape, ))  # 500
X = model_input

# 1st hidden layer
X_W1 = Dense(units=64)(X)  # 64
H1 = ReLU()(X_W1)

# 2nd hidden layer
H1_W2 = Dense(units=64)(H1)  # 64
H2 = ReLU()(H1_W2)

# output layer
H2_W3 = Dense(units=output_shape)(H2)  # 4
H3 = Softmax()(H2_W3)

model_output = H3

# create model
model = Model(inputs=[model_input], outputs=[model_output])

# loss function & optimizer
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# show model construction
model.summary()

Model: "model_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_5 (InputLayer)         [(None, 25)]              0         
_________________________________________________________________
dense_12 (Dense)             (None, 64)                1664      
_________________________________________________________________
re_lu_8 (ReLU)               (None, 64)                0         
_________________________________________________________________
dense_13 (Dense)             (None, 64)                4160      
_________________________________________________________________
re_lu_9 (ReLU)               (None, 64)                0         
_________________________________________________________________
dense_14 (Dense)             (None, 4)                 260       
_________________________________________________________________
softmax_4 (Softmax)          (None, 4)                 0   

In [340]:
from keras.callbacks import CSVLogger

# training setting
epochs = 25
batch_size = 128

# training!
history = model.fit(X_train, y_train, 
                    epochs=epochs, 
                    batch_size=batch_size, 
                    validation_data = (X_test, y_test))
print('training finish')

Epoch 1/25


C:\Users\ASUS\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\framework\indexed_slices.py:447: UserWarning: Converting sparse IndexedSlices(IndexedSlices(indices=Tensor("gradient_tape/model_4/dense_12/embedding_lookup_sparse/Reshape_1:0", shape=(None,), dtype=int32), values=Tensor("gradient_tape/model_4/dense_12/embedding_lookup_sparse/Reshape:0", shape=(None, 64), dtype=float32), dense_shape=Tensor("gradient_tape/model_4/dense_12/embedding_lookup_sparse/Cast:0", shape=(2,), dtype=int32))) to a dense Tensor of unknown shape. This may consume a large amount of memory.
  warnings.warn(


23/23 [==============================] - 1s 6ms/step - loss: 1.3655 - accuracy: 0.2965 - val_loss: 1.3382 - val_accuracy: 0.3628
Epoch 2/25
23/23 [==============================] - 0s 1ms/step - loss: 1.3415 - accuracy: 0.3159 - val_loss: 1.3409 - val_accuracy: 0.3841
Epoch 3/25
23/23 [==============================] - 0s 1ms/step - loss: 1.3372 - accuracy: 0.3305 - val_loss: 1.3434 - val_accuracy: 0.3323
Epoch 4/25
23/23 [==============================] - 0s 1ms/step - loss: 1.3329 - accuracy: 0.3325 - val_loss: 1.3377 - val_accuracy: 0.3841
Epoch 5/25
23/23 [==============================] - 0s 5ms/step - loss: 1.3304 - accuracy: 0.3366 - val_loss: 1.3472 - val_accuracy: 0.3232
Epoch 6/25
23/23 [==============================] - 0s 1ms/step - loss: 1.3272 - accuracy: 0.3441 - val_loss: 1.3383 - val_accuracy: 0.3689
Epoch 7/25
23/23 [==============================] - 0s 1ms/step - loss: 1.3252 - accuracy: 0.3441 - val_loss: 1.3464 - val_accuracy: 0.3384
Epoch 8/25
23/23 [=============

In [341]:
## predict
pred_result = model.predict(X_test, batch_size=128)
pred_result[:5]

array([[0.37069654, 0.0546974 , 0.24389957, 0.3307064 ],
       [0.39125445, 0.11186276, 0.14442901, 0.3524538 ],
       [0.23108695, 0.16807064, 0.23575722, 0.3650852 ],
       [0.23880379, 0.1195078 , 0.22292414, 0.41876432],
       [0.35661703, 0.13041832, 0.23047099, 0.28249368]], dtype=float32)

In [342]:
pred_result = label_decode(label_encoder, pred_result)
pred_result[:5]

array(['afternoon', 'afternoon', 'night', 'night', 'afternoon'],
      dtype=object)

In [343]:
from sklearn.metrics import accuracy_score

print('testing accuracy: {}'.format(round(accuracy_score(label_decode(label_encoder, y_test), pred_result), 2)))

testing accuracy: 0.33


---KNN---


In [344]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

In [345]:
train_data , test_data , train_label , test_label = train_test_split(df['locate'],df['time_zone'],test_size=0.2)

In [346]:
train_data = BOW.transform(train_data)
test_data = BOW.transform(test_data)
train_data.shape

(2617, 25)

In [347]:
test_data.shape

(655, 25)

In [348]:
knn = KNeighborsClassifier()
knn.fit(train_data,train_label)

KNeighborsClassifier()

In [349]:
knn.score(test_data,test_label)

0.29465648854961835

---如何預測---

In [350]:
test = BOW.transform(['乾你媽的'])



In [351]:
DT_model.predict(test)[0]

'afternoon'

In [352]:
target = df['發生地點']

In [353]:
target_bow = BOW.transform(target)

In [354]:
predict = DT_model.predict(target_bow)

In [355]:
predict = pd.Series(predict)

In [356]:
res = pd.concat([target,predict], axis=1, ignore_index=True)

In [357]:
res.to_csv('result.csv', index=False, encoding='utf-8-sig')